export const idlFactory = ({ IDL }) => {
  const GuideHighlight = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'stepId' : IDL.Text,
    'highlightType' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'selector' : IDL.Text,
  });
  const GuideNavigation = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'stepId' : IDL.Text,
    'previous' : IDL.Opt(IDL.Text),
    'exit' : IDL.Bool,
    'createdAt' : IDL.Int,
    'skip' : IDL.Bool,
    'updatedAt' : IDL.Int,
    'nextStep' : IDL.Opt(IDL.Text),
  });
  const GuideSection = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'steps' : IDL.Vec(IDL.Text),
  });
  const GuideStep = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Record({
      'active' : IDL.Bool,
      'skipped' : IDL.Bool,
      'completed' : IDL.Bool,
    }),
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'createdAt' : IDL.Int,
    'navigation' : IDL.Record({
      'previous' : IDL.Opt(IDL.Text),
      'exit' : IDL.Bool,
      'next' : IDL.Opt(IDL.Text),
      'skip' : IDL.Bool,
    }),
    'section' : IDL.Text,
    'description' : IDL.Text,
    'highlightSelector' : IDL.Text,
    'version' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'progress' : IDL.Record({
      'currentStep' : IDL.Nat,
      'totalSteps' : IDL.Nat,
    }),
    'mobile' : IDL.Record({ 'optimized' : IDL.Bool, 'responsive' : IDL.Bool }),
    'visual' : IDL.Record({
      'arrow' : IDL.Bool,
      'animation' : IDL.Bool,
      'border' : IDL.Bool,
      'tooltip' : IDL.Bool,
      'spotlight' : IDL.Bool,
    }),
    'accessibility' : IDL.Record({
      'contrast' : IDL.Bool,
      'keyboardNavigation' : IDL.Bool,
      'screenReader' : IDL.Bool,
    }),
  });
  const GuideTooltip = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'stepId' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'position' : IDL.Text,
  });
  const NeumannPeriod = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'nrnAllocation' : IDL.Nat,
    'endTimestamp' : IDL.Int,
    'startTimestamp' : IDL.Int,
    'cwuTarget' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FileReference = IDL.Record({ 'hash' : IDL.Text, 'path' : IDL.Text });
  const GovernanceLock = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'unlockTimestamp' : IDL.Int,
    'locker' : IDL.Principal,
    'lockTimestamp' : IDL.Int,
    'proposalId' : IDL.Text,
    'lockedAmount' : IDL.Nat,
  });
  const GovernancePhase = IDL.Variant({
    'locking' : IDL.Null,
    'voting' : IDL.Null,
    'proposalSubmission' : IDL.Null,
  });
  const GovernanceProposal = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'createdAt' : IDL.Int,
    'feePaid' : IDL.Nat,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'phase' : GovernancePhase,
  });
  const GovernanceVote = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'voter' : IDL.Principal,
    'vote' : IDL.Bool,
    'timestamp' : IDL.Int,
    'proposalId' : IDL.Text,
  });
  const GuideAchievement = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'user' : IDL.Principal,
    'achievedAt' : IDL.Int,
    'achievement' : IDL.Text,
  });
  const GuidePreference = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'theme' : IDL.Text,
    'createdAt' : IDL.Int,
    'user' : IDL.Principal,
    'updatedAt' : IDL.Int,
    'detailLevel' : IDL.Nat,
    'tutorialSpeed' : IDL.Nat,
  });
  const GuideProgress = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'skippedSteps' : IDL.Vec(IDL.Text),
    'startedAt' : IDL.Int,
    'user' : IDL.Principal,
    'updatedAt' : IDL.Int,
    'currentStep' : IDL.Text,
    'completedSteps' : IDL.Vec(IDL.Text),
  });
  const GuideStatus = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'skippedSteps' : IDL.Vec(IDL.Text),
    'startedAt' : IDL.Int,
    'user' : IDL.Principal,
    'updatedAt' : IDL.Int,
    'currentStep' : IDL.Text,
    'completedSteps' : IDL.Vec(IDL.Text),
  });
  const GuideVersion = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'version' : IDL.Nat,
    'updatedAt' : IDL.Int,
  });
  const PoccCwuStats = IDL.Record({
    'id' : IDL.Text,
    'totalCwu' : IDL.Float64,
    'timestamp' : IDL.Int,
    'periodId' : IDL.Text,
    'workerCount' : IDL.Nat,
  });
  const PoccEpoch = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'endTimestamp' : IDL.Int,
    'periodId' : IDL.Text,
    'startTimestamp' : IDL.Int,
  });
  const PoccPool = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'creator' : IDL.Principal,
    'totalBonded' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'effectiveShareCap' : IDL.Float64,
  });
  const PoccProof = IDL.Record({
    'id' : IDL.Text,
    'cwu' : IDL.Float64,
    'status' : IDL.Text,
    'workerId' : IDL.Text,
    'proofData' : IDL.Text,
    'taskId' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const PoccReward = IDL.Record({
    'id' : IDL.Text,
    'cwu' : IDL.Float64,
    'status' : IDL.Text,
    'workerId' : IDL.Text,
    'nrnReward' : IDL.Nat,
    'timestamp' : IDL.Int,
    'periodId' : IDL.Text,
  });
  const PoccSlashing = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'workerId' : IDL.Text,
    'penaltyAmount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'reason' : IDL.Text,
  });
  const PoccTask = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'difficulty' : IDL.Nat,
    'createdAt' : IDL.Int,
    'seed' : IDL.Text,
    'payload' : IDL.Text,
  });
  const BondType = IDL.Variant({ 'icp' : IDL.Null, 'nrn' : IDL.Null });
  const PoccWorker = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'principal' : IDL.Principal,
    'reputationScore' : IDL.Float64,
    'hardwareAttestation' : IDL.Text,
    'registrationTimestamp' : IDL.Int,
    'bondType' : BondType,
    'bondAmount' : IDL.Nat,
  });
  return IDL.Service({
    'addGuideAchievement' : IDL.Func([IDL.Text], [IDL.Text], []),
    'addGuideHighlight' : IDL.Func([GuideHighlight], [], []),
    'addGuideNavigation' : IDL.Func([GuideNavigation], [], []),
    'addGuideSection' : IDL.Func([GuideSection], [], []),
    'addGuideStep' : IDL.Func([GuideStep], [], []),
    'addGuideTooltip' : IDL.Func([GuideTooltip], [], []),
    'addGuideVersion' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'addNeumannPeriod' : IDL.Func([NeumannPeriod], [], []),
    'addPoccCwuStats' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'addPoccEpoch' : IDL.Func([IDL.Text, IDL.Int, IDL.Int], [IDL.Text], []),
    'addPoccSlashing' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'castGovernanceVote' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Text], []),
    'createGovernanceProposal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'createPoccPool' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64],
        [IDL.Text],
        [],
      ),
    'createPoccTask' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Text], []),
    'distributePoccReward' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'dropFileReference' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCreatorNernSupply' : IDL.Func([], [IDL.Nat], ['query']),
    'getCurrentNeumannPeriod' : IDL.Func(
        [],
        [IDL.Opt(NeumannPeriod)],
        ['query'],
      ),
    'getDocumentationContent' : IDL.Func([], [IDL.Text], ['query']),
    'getDocumentationSections' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
    'getGovernanceLock' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GovernanceLock)],
        ['query'],
      ),
    'getGovernanceLockingInstructions' : IDL.Func([], [IDL.Text], ['query']),
    'getGovernancePenaltyInstructions' : IDL.Func([], [IDL.Text], ['query']),
    'getGovernancePhaseDurations' : IDL.Func(
        [],
        [IDL.Int, IDL.Int, IDL.Int],
        ['query'],
      ),
    'getGovernancePhaseStatus' : IDL.Func([], [IDL.Text], ['query']),
    'getGovernanceProofOfAttendanceInstructions' : IDL.Func(
        [],
        [IDL.Text],
        ['query'],
      ),
    'getGovernanceProposal' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GovernanceProposal)],
        ['query'],
      ),
    'getGovernanceProposalStats' : IDL.Func(
        [IDL.Text],
        [IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'getGovernanceSystemOverview' : IDL.Func([], [IDL.Text], ['query']),
    'getGovernanceSystemStatus' : IDL.Func([], [IDL.Text], ['query']),
    'getGovernanceVote' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GovernanceVote)],
        ['query'],
      ),
    'getGovernanceVotingInstructions' : IDL.Func([], [IDL.Text], ['query']),
    'getGuideAchievement' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GuideAchievement)],
        ['query'],
      ),
    'getGuideHighlight' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GuideHighlight)],
        ['query'],
      ),
    'getGuideNavigation' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GuideNavigation)],
        ['query'],
      ),
    'getGuidePreference' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GuidePreference)],
        ['query'],
      ),
    'getGuideProgress' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GuideProgress)],
        ['query'],
      ),
    'getGuideSection' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GuideSection)],
        ['query'],
      ),
    'getGuideStatus' : IDL.Func([IDL.Text], [IDL.Opt(GuideStatus)], ['query']),
    'getGuideStep' : IDL.Func([IDL.Text], [IDL.Opt(GuideStep)], ['query']),
    'getGuideTooltip' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GuideTooltip)],
        ['query'],
      ),
    'getGuideVersion' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GuideVersion)],
        ['query'],
      ),
    'getLockedNernStats' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getLockedNernStatus' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getMineableNernSupply' : IDL.Func([], [IDL.Nat], ['query']),
    'getNeumannPeriod' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(NeumannPeriod)],
        ['query'],
      ),
    'getNeumannPeriodBreakdown' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getPoccCwuFormula' : IDL.Func([], [IDL.Text], ['query']),
    'getPoccCwuStats' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PoccCwuStats)],
        ['query'],
      ),
    'getPoccEpoch' : IDL.Func([IDL.Text], [IDL.Opt(PoccEpoch)], ['query']),
    'getPoccEpochDuration' : IDL.Func([], [IDL.Int], ['query']),
    'getPoccMinimumBond' : IDL.Func([], [IDL.Nat], ['query']),
    'getPoccNeumannPeriods' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getPoccPool' : IDL.Func([IDL.Text], [IDL.Opt(PoccPool)], ['query']),
    'getPoccProof' : IDL.Func([IDL.Text], [IDL.Opt(PoccProof)], ['query']),
    'getPoccReward' : IDL.Func([IDL.Text], [IDL.Opt(PoccReward)], ['query']),
    'getPoccRewardFormula' : IDL.Func([], [IDL.Text], ['query']),
    'getPoccSlashing' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PoccSlashing)],
        ['query'],
      ),
    'getPoccTask' : IDL.Func([IDL.Text], [IDL.Opt(PoccTask)], ['query']),
    'getPoccWorker' : IDL.Func([IDL.Text], [IDL.Opt(PoccWorker)], ['query']),
    'getTotalNernSupply' : IDL.Func([], [IDL.Nat], ['query']),
    'getUnlockInstructions' : IDL.Func([], [IDL.Text], ['query']),
    'getUnlockStatus' : IDL.Func([], [IDL.Text], ['query']),
    'getUnlockSystemStatus' : IDL.Func([], [IDL.Text], ['query']),
    'getUnlockableNernInstructions' : IDL.Func([], [IDL.Text], ['query']),
    'getUnlockableNernLocks' : IDL.Func(
        [],
        [IDL.Vec(GovernanceLock)],
        ['query'],
      ),
    'getUnlockableNernStats' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
    'getUnlockableNernStatus' : IDL.Func([], [IDL.Text], ['query']),
    'getUnlockableNernSystemStatus' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWhitepaperContent' : IDL.Func([], [IDL.Text], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'listGovernanceProposals' : IDL.Func(
        [],
        [IDL.Vec(GovernanceProposal)],
        ['query'],
      ),
    'listGuideHighlights' : IDL.Func([], [IDL.Vec(GuideHighlight)], ['query']),
    'listGuideNavigation' : IDL.Func([], [IDL.Vec(GuideNavigation)], ['query']),
    'listGuideSections' : IDL.Func([], [IDL.Vec(GuideSection)], ['query']),
    'listGuideSteps' : IDL.Func([], [IDL.Vec(GuideStep)], ['query']),
    'listGuideTooltips' : IDL.Func([], [IDL.Vec(GuideTooltip)], ['query']),
    'listGuideVersions' : IDL.Func([], [IDL.Vec(GuideVersion)], ['query']),
    'listMyGovernanceLocks' : IDL.Func(
        [],
        [IDL.Vec(GovernanceLock)],
        ['query'],
      ),
    'listMyGovernanceVotes' : IDL.Func(
        [],
        [IDL.Vec(GovernanceVote)],
        ['query'],
      ),
    'listMyGuideAchievements' : IDL.Func(
        [],
        [IDL.Vec(GuideAchievement)],
        ['query'],
      ),
    'listMyGuidePreferences' : IDL.Func(
        [],
        [IDL.Vec(GuidePreference)],
        ['query'],
      ),
    'listMyGuideProgress' : IDL.Func([], [IDL.Vec(GuideProgress)], ['query']),
    'listMyGuideStatus' : IDL.Func([], [IDL.Vec(GuideStatus)], ['query']),
    'listNeumannPeriods' : IDL.Func([], [IDL.Vec(NeumannPeriod)], ['query']),
    'listPoccCwuStats' : IDL.Func([], [IDL.Vec(PoccCwuStats)], ['query']),
    'listPoccEpochs' : IDL.Func([], [IDL.Vec(PoccEpoch)], ['query']),
    'listPoccPools' : IDL.Func([], [IDL.Vec(PoccPool)], ['query']),
    'listPoccProofs' : IDL.Func([], [IDL.Vec(PoccProof)], ['query']),
    'listPoccRewards' : IDL.Func([], [IDL.Vec(PoccReward)], ['query']),
    'listPoccSlashings' : IDL.Func([], [IDL.Vec(PoccSlashing)], ['query']),
    'listPoccTasks' : IDL.Func([], [IDL.Vec(PoccTask)], ['query']),
    'listPoccWorkers' : IDL.Func([], [IDL.Vec(PoccWorker)], ['query']),
    'lockNernForGovernance' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
    'lockNernForProofOfAttendance' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'registerPoccWorker' : IDL.Func(
        [BondType, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setGuidePreference' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'startGuideProgress' : IDL.Func([IDL.Text], [IDL.Text], []),
    'startGuideStatus' : IDL.Func([IDL.Text], [IDL.Text], []),
    'submitPoccProof' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Text],
        [],
      ),
    'unlockNern' : IDL.Func([IDL.Text], [], []),
    'updateGuidePreference' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateGuideProgress' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'updateGuideStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
  });
};
export const init = ({ IDL }) => { return []; };
