/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VerifierValidation {
    verifierPrincipal: Principal;
    validationResult: boolean;
    validationTimestamp: bigint;
    validationSignature: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface MiningWorker {
    id: string;
    status: string;
    bondToken: string;
    cryptographicIdentity: string;
    owner: Principal;
    hardwareSpecs: string;
    registeredAt: bigint;
    verificationStatus: string;
    bondAmount: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface MiningProof {
    workerId: string;
    rewardAmount: number;
    cwuAmount: number;
    owner: Principal;
    computationHash: string;
    rewardStatus: string;
    timestamp: bigint;
    cryptographicSignature: string;
    verifierConsensus: Array<VerifierValidation>;
    verificationStatus: string;
    proofId: string;
}
export interface DecentralizationMetrics {
    verifiedProofs: bigint;
    totalWorkers: bigint;
    lastUpdated: bigint;
    activeWorkers: bigint;
    decentralizationScore: number;
    totalProofs: bigint;
    averageVerifiers: number;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface MiningAuditEntry {
    action: string;
    entryId: string;
    timestamp: bigint;
    details: string;
    actorPrincipal: Principal;
    proofId: string;
}
export interface FileReference {
    hash: string;
    path: string;
}
export interface UserProfile {
    votingAbility: boolean;
    principal: Principal;
    completedRevolutionaryUpgrades: boolean;
    privacyTips: Array<string>;
    completedWelcome: boolean;
    name: string;
    onboardingProgress: bigint;
    onboardingCompleted: boolean;
    completedDocumentation: boolean;
    completedWhitepaper: boolean;
    completedGetStarted: boolean;
    sessionStatus: string;
    completedTutorial: boolean;
}
export interface http_header {
    value: string;
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deactivateMiningWorker(workerId: string): Promise<void>;
    distributeMiningReward(proofId: string, rewardAmount: number): Promise<void>;
    dropFileReference(path: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDecentralizationMetrics(): Promise<DecentralizationMetrics>;
    getFileReference(path: string): Promise<FileReference>;
    getMiningAuditLog(): Promise<Array<MiningAuditEntry>>;
    getMiningProof(proofId: string): Promise<MiningProof | null>;
    getMiningWorker(workerId: string): Promise<MiningWorker | null>;
    getMyMiningAuditEntries(): Promise<Array<MiningAuditEntry>>;
    getNeronFirstPost(): Promise<string>;
    getOnboardingProgress(): Promise<bigint>;
    getPrincipalInfo(): Promise<Principal>;
    getPrivacyTips(): Promise<Array<string>>;
    getSessionStatus(): Promise<string>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVotingAbilityStatus(): Promise<boolean>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isOnboardingCompleted(): Promise<boolean>;
    listFileReferences(): Promise<Array<FileReference>>;
    listMyMiningProofs(): Promise<Array<MiningProof>>;
    listMyMiningWorkers(): Promise<Array<MiningWorker>>;
    markDocumentationCompleted(completed: boolean): Promise<void>;
    markGetStartedCompleted(completed: boolean): Promise<void>;
    markRevolutionaryUpgradesCompleted(completed: boolean): Promise<void>;
    markTutorialCompleted(completed: boolean): Promise<void>;
    markWelcomeCompleted(completed: boolean): Promise<void>;
    markWhitepaperCompleted(completed: boolean): Promise<void>;
    registerFileReference(path: string, hash: string): Promise<void>;
    registerMiningWorker(cryptographicIdentity: string, hardwareSpecs: string, bondAmount: bigint, bondToken: string): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitMiningProof(workerId: string, computationHash: string, cryptographicSignature: string, cwuAmount: number): Promise<string>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateDisplayName(newName: string): Promise<void>;
    updateOnboardingProgress(progress: bigint, completed: boolean): Promise<void>;
    updateSessionStatus(status: string): Promise<void>;
    updateVotingAbilityStatus(status: boolean): Promise<void>;
    verifyMiningProof(proofId: string, validationResult: boolean, validationSignature: string): Promise<void>;
}
import type { MiningProof as _MiningProof, MiningWorker as _MiningWorker, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async deactivateMiningWorker(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateMiningWorker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateMiningWorker(arg0);
            return result;
        }
    }
    async distributeMiningReward(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.distributeMiningReward(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.distributeMiningReward(arg0, arg1);
            return result;
        }
    }
    async dropFileReference(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dropFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dropFileReference(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async getDecentralizationMetrics(): Promise<DecentralizationMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getDecentralizationMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDecentralizationMetrics();
            return result;
        }
    }
    async getFileReference(arg0: string): Promise<FileReference> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileReference(arg0);
            return result;
        }
    }
    async getMiningAuditLog(): Promise<Array<MiningAuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMiningAuditLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMiningAuditLog();
            return result;
        }
    }
    async getMiningProof(arg0: string): Promise<MiningProof | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMiningProof(arg0);
                return from_candid_opt_n6(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMiningProof(arg0);
            return from_candid_opt_n6(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMiningWorker(arg0: string): Promise<MiningWorker | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMiningWorker(arg0);
                return from_candid_opt_n7(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMiningWorker(arg0);
            return from_candid_opt_n7(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMyMiningAuditEntries(): Promise<Array<MiningAuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMiningAuditEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMiningAuditEntries();
            return result;
        }
    }
    async getNeronFirstPost(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getNeronFirstPost();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNeronFirstPost();
            return result;
        }
    }
    async getOnboardingProgress(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getOnboardingProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOnboardingProgress();
            return result;
        }
    }
    async getPrincipalInfo(): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrincipalInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrincipalInfo();
            return result;
        }
    }
    async getPrivacyTips(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrivacyTips();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrivacyTips();
            return result;
        }
    }
    async getSessionStatus(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionStatus();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async getVotingAbilityStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getVotingAbilityStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVotingAbilityStatus();
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isOnboardingCompleted(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOnboardingCompleted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOnboardingCompleted();
            return result;
        }
    }
    async listFileReferences(): Promise<Array<FileReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFileReferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFileReferences();
            return result;
        }
    }
    async listMyMiningProofs(): Promise<Array<MiningProof>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyMiningProofs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyMiningProofs();
            return result;
        }
    }
    async listMyMiningWorkers(): Promise<Array<MiningWorker>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyMiningWorkers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyMiningWorkers();
            return result;
        }
    }
    async markDocumentationCompleted(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markDocumentationCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markDocumentationCompleted(arg0);
            return result;
        }
    }
    async markGetStartedCompleted(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markGetStartedCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markGetStartedCompleted(arg0);
            return result;
        }
    }
    async markRevolutionaryUpgradesCompleted(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markRevolutionaryUpgradesCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markRevolutionaryUpgradesCompleted(arg0);
            return result;
        }
    }
    async markTutorialCompleted(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markTutorialCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTutorialCompleted(arg0);
            return result;
        }
    }
    async markWelcomeCompleted(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markWelcomeCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markWelcomeCompleted(arg0);
            return result;
        }
    }
    async markWhitepaperCompleted(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markWhitepaperCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markWhitepaperCompleted(arg0);
            return result;
        }
    }
    async registerFileReference(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFileReference(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFileReference(arg0, arg1);
            return result;
        }
    }
    async registerMiningWorker(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerMiningWorker(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerMiningWorker(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitMiningProof(arg0: string, arg1: string, arg2: string, arg3: number): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMiningProof(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMiningProof(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateDisplayName(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDisplayName(arg0);
            return result;
        }
    }
    async updateOnboardingProgress(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOnboardingProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOnboardingProgress(arg0, arg1);
            return result;
        }
    }
    async updateSessionStatus(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSessionStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSessionStatus(arg0);
            return result;
        }
    }
    async updateVotingAbilityStatus(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVotingAbilityStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVotingAbilityStatus(arg0);
            return result;
        }
    }
    async verifyMiningProof(arg0: string, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyMiningProof(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyMiningProof(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_UserRole_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MiningProof]): MiningProof | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MiningWorker]): MiningWorker | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(uploadFile, downloadFile, value);
}
function to_candid_variant_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
