/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DecentralizationMetrics {
  'verifiedProofs' : bigint,
  'totalWorkers' : bigint,
  'lastUpdated' : bigint,
  'activeWorkers' : bigint,
  'decentralizationScore' : number,
  'totalProofs' : bigint,
  'averageVerifiers' : number,
}
export interface FileReference { 'hash' : string, 'path' : string }
export interface MiningAuditEntry {
  'action' : string,
  'entryId' : string,
  'timestamp' : bigint,
  'details' : string,
  'actorPrincipal' : Principal,
  'proofId' : string,
}
export interface MiningProof {
  'workerId' : string,
  'rewardAmount' : number,
  'cwuAmount' : number,
  'owner' : Principal,
  'computationHash' : string,
  'rewardStatus' : string,
  'timestamp' : bigint,
  'cryptographicSignature' : string,
  'verifierConsensus' : Array<VerifierValidation>,
  'verificationStatus' : string,
  'proofId' : string,
}
export interface MiningWorker {
  'id' : string,
  'status' : string,
  'bondToken' : string,
  'cryptographicIdentity' : string,
  'owner' : Principal,
  'hardwareSpecs' : string,
  'registeredAt' : bigint,
  'verificationStatus' : string,
  'bondAmount' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'votingAbility' : boolean,
  'principal' : Principal,
  'completedRevolutionaryUpgrades' : boolean,
  'privacyTips' : Array<string>,
  'completedWelcome' : boolean,
  'name' : string,
  'onboardingProgress' : bigint,
  'onboardingCompleted' : boolean,
  'completedDocumentation' : boolean,
  'completedWhitepaper' : boolean,
  'completedGetStarted' : boolean,
  'sessionStatus' : string,
  'completedTutorial' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VerifierValidation {
  'verifierPrincipal' : Principal,
  'validationResult' : boolean,
  'validationTimestamp' : bigint,
  'validationSignature' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deactivateMiningWorker' : ActorMethod<[string], undefined>,
  'distributeMiningReward' : ActorMethod<[string, number], undefined>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDecentralizationMetrics' : ActorMethod<[], DecentralizationMetrics>,
  'getFileReference' : ActorMethod<[string], FileReference>,
  'getMiningAuditLog' : ActorMethod<[], Array<MiningAuditEntry>>,
  'getMiningProof' : ActorMethod<[string], [] | [MiningProof]>,
  'getMiningWorker' : ActorMethod<[string], [] | [MiningWorker]>,
  'getMyMiningAuditEntries' : ActorMethod<[], Array<MiningAuditEntry>>,
  'getNeronFirstPost' : ActorMethod<[], string>,
  'getOnboardingProgress' : ActorMethod<[], bigint>,
  'getPrincipalInfo' : ActorMethod<[], Principal>,
  'getPrivacyTips' : ActorMethod<[], Array<string>>,
  'getSessionStatus' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVotingAbilityStatus' : ActorMethod<[], boolean>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOnboardingCompleted' : ActorMethod<[], boolean>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'listMyMiningProofs' : ActorMethod<[], Array<MiningProof>>,
  'listMyMiningWorkers' : ActorMethod<[], Array<MiningWorker>>,
  'markDocumentationCompleted' : ActorMethod<[boolean], undefined>,
  'markGetStartedCompleted' : ActorMethod<[boolean], undefined>,
  'markRevolutionaryUpgradesCompleted' : ActorMethod<[boolean], undefined>,
  'markTutorialCompleted' : ActorMethod<[boolean], undefined>,
  'markWelcomeCompleted' : ActorMethod<[boolean], undefined>,
  'markWhitepaperCompleted' : ActorMethod<[boolean], undefined>,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'registerMiningWorker' : ActorMethod<
    [string, string, bigint, string],
    string
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitMiningProof' : ActorMethod<[string, string, string, number], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateDisplayName' : ActorMethod<[string], undefined>,
  'updateOnboardingProgress' : ActorMethod<[bigint, boolean], undefined>,
  'updateSessionStatus' : ActorMethod<[string], undefined>,
  'updateVotingAbilityStatus' : ActorMethod<[boolean], undefined>,
  'verifyMiningProof' : ActorMethod<[string, boolean, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];