/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'votingAbility' : IDL.Bool,
  'principal' : IDL.Principal,
  'completedRevolutionaryUpgrades' : IDL.Bool,
  'privacyTips' : IDL.Vec(IDL.Text),
  'completedWelcome' : IDL.Bool,
  'name' : IDL.Text,
  'onboardingProgress' : IDL.Nat,
  'onboardingCompleted' : IDL.Bool,
  'completedDocumentation' : IDL.Bool,
  'completedWhitepaper' : IDL.Bool,
  'completedGetStarted' : IDL.Bool,
  'sessionStatus' : IDL.Text,
  'completedTutorial' : IDL.Bool,
});
export const DecentralizationMetrics = IDL.Record({
  'verifiedProofs' : IDL.Nat,
  'totalWorkers' : IDL.Nat,
  'lastUpdated' : IDL.Int,
  'activeWorkers' : IDL.Nat,
  'decentralizationScore' : IDL.Float64,
  'totalProofs' : IDL.Nat,
  'averageVerifiers' : IDL.Float64,
});
export const FileReference = IDL.Record({
  'hash' : IDL.Text,
  'path' : IDL.Text,
});
export const MiningAuditEntry = IDL.Record({
  'action' : IDL.Text,
  'entryId' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'actorPrincipal' : IDL.Principal,
  'proofId' : IDL.Text,
});
export const VerifierValidation = IDL.Record({
  'verifierPrincipal' : IDL.Principal,
  'validationResult' : IDL.Bool,
  'validationTimestamp' : IDL.Int,
  'validationSignature' : IDL.Text,
});
export const MiningProof = IDL.Record({
  'workerId' : IDL.Text,
  'rewardAmount' : IDL.Float64,
  'cwuAmount' : IDL.Float64,
  'owner' : IDL.Principal,
  'computationHash' : IDL.Text,
  'rewardStatus' : IDL.Text,
  'timestamp' : IDL.Int,
  'cryptographicSignature' : IDL.Text,
  'verifierConsensus' : IDL.Vec(VerifierValidation),
  'verificationStatus' : IDL.Text,
  'proofId' : IDL.Text,
});
export const MiningWorker = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'bondToken' : IDL.Text,
  'cryptographicIdentity' : IDL.Text,
  'owner' : IDL.Principal,
  'hardwareSpecs' : IDL.Text,
  'registeredAt' : IDL.Int,
  'verificationStatus' : IDL.Text,
  'bondAmount' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deactivateMiningWorker' : IDL.Func([IDL.Text], [], []),
  'distributeMiningReward' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'dropFileReference' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDecentralizationMetrics' : IDL.Func(
      [],
      [DecentralizationMetrics],
      ['query'],
    ),
  'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
  'getMiningAuditLog' : IDL.Func([], [IDL.Vec(MiningAuditEntry)], ['query']),
  'getMiningProof' : IDL.Func([IDL.Text], [IDL.Opt(MiningProof)], ['query']),
  'getMiningWorker' : IDL.Func([IDL.Text], [IDL.Opt(MiningWorker)], ['query']),
  'getMyMiningAuditEntries' : IDL.Func(
      [],
      [IDL.Vec(MiningAuditEntry)],
      ['query'],
    ),
  'getNeronFirstPost' : IDL.Func([], [IDL.Text], ['query']),
  'getOnboardingProgress' : IDL.Func([], [IDL.Nat], ['query']),
  'getPrincipalInfo' : IDL.Func([], [IDL.Principal], ['query']),
  'getPrivacyTips' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getSessionStatus' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVotingAbilityStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOnboardingCompleted' : IDL.Func([], [IDL.Bool], ['query']),
  'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'listMyMiningProofs' : IDL.Func([], [IDL.Vec(MiningProof)], ['query']),
  'listMyMiningWorkers' : IDL.Func([], [IDL.Vec(MiningWorker)], ['query']),
  'markDocumentationCompleted' : IDL.Func([IDL.Bool], [], []),
  'markGetStartedCompleted' : IDL.Func([IDL.Bool], [], []),
  'markRevolutionaryUpgradesCompleted' : IDL.Func([IDL.Bool], [], []),
  'markTutorialCompleted' : IDL.Func([IDL.Bool], [], []),
  'markWelcomeCompleted' : IDL.Func([IDL.Bool], [], []),
  'markWhitepaperCompleted' : IDL.Func([IDL.Bool], [], []),
  'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'registerMiningWorker' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitMiningProof' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Text],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateDisplayName' : IDL.Func([IDL.Text], [], []),
  'updateOnboardingProgress' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateSessionStatus' : IDL.Func([IDL.Text], [], []),
  'updateVotingAbilityStatus' : IDL.Func([IDL.Bool], [], []),
  'verifyMiningProof' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'votingAbility' : IDL.Bool,
    'principal' : IDL.Principal,
    'completedRevolutionaryUpgrades' : IDL.Bool,
    'privacyTips' : IDL.Vec(IDL.Text),
    'completedWelcome' : IDL.Bool,
    'name' : IDL.Text,
    'onboardingProgress' : IDL.Nat,
    'onboardingCompleted' : IDL.Bool,
    'completedDocumentation' : IDL.Bool,
    'completedWhitepaper' : IDL.Bool,
    'completedGetStarted' : IDL.Bool,
    'sessionStatus' : IDL.Text,
    'completedTutorial' : IDL.Bool,
  });
  const DecentralizationMetrics = IDL.Record({
    'verifiedProofs' : IDL.Nat,
    'totalWorkers' : IDL.Nat,
    'lastUpdated' : IDL.Int,
    'activeWorkers' : IDL.Nat,
    'decentralizationScore' : IDL.Float64,
    'totalProofs' : IDL.Nat,
    'averageVerifiers' : IDL.Float64,
  });
  const FileReference = IDL.Record({ 'hash' : IDL.Text, 'path' : IDL.Text });
  const MiningAuditEntry = IDL.Record({
    'action' : IDL.Text,
    'entryId' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'actorPrincipal' : IDL.Principal,
    'proofId' : IDL.Text,
  });
  const VerifierValidation = IDL.Record({
    'verifierPrincipal' : IDL.Principal,
    'validationResult' : IDL.Bool,
    'validationTimestamp' : IDL.Int,
    'validationSignature' : IDL.Text,
  });
  const MiningProof = IDL.Record({
    'workerId' : IDL.Text,
    'rewardAmount' : IDL.Float64,
    'cwuAmount' : IDL.Float64,
    'owner' : IDL.Principal,
    'computationHash' : IDL.Text,
    'rewardStatus' : IDL.Text,
    'timestamp' : IDL.Int,
    'cryptographicSignature' : IDL.Text,
    'verifierConsensus' : IDL.Vec(VerifierValidation),
    'verificationStatus' : IDL.Text,
    'proofId' : IDL.Text,
  });
  const MiningWorker = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'bondToken' : IDL.Text,
    'cryptographicIdentity' : IDL.Text,
    'owner' : IDL.Principal,
    'hardwareSpecs' : IDL.Text,
    'registeredAt' : IDL.Int,
    'verificationStatus' : IDL.Text,
    'bondAmount' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deactivateMiningWorker' : IDL.Func([IDL.Text], [], []),
    'distributeMiningReward' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'dropFileReference' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDecentralizationMetrics' : IDL.Func(
        [],
        [DecentralizationMetrics],
        ['query'],
      ),
    'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
    'getMiningAuditLog' : IDL.Func([], [IDL.Vec(MiningAuditEntry)], ['query']),
    'getMiningProof' : IDL.Func([IDL.Text], [IDL.Opt(MiningProof)], ['query']),
    'getMiningWorker' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MiningWorker)],
        ['query'],
      ),
    'getMyMiningAuditEntries' : IDL.Func(
        [],
        [IDL.Vec(MiningAuditEntry)],
        ['query'],
      ),
    'getNeronFirstPost' : IDL.Func([], [IDL.Text], ['query']),
    'getOnboardingProgress' : IDL.Func([], [IDL.Nat], ['query']),
    'getPrincipalInfo' : IDL.Func([], [IDL.Principal], ['query']),
    'getPrivacyTips' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getSessionStatus' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVotingAbilityStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOnboardingCompleted' : IDL.Func([], [IDL.Bool], ['query']),
    'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'listMyMiningProofs' : IDL.Func([], [IDL.Vec(MiningProof)], ['query']),
    'listMyMiningWorkers' : IDL.Func([], [IDL.Vec(MiningWorker)], ['query']),
    'markDocumentationCompleted' : IDL.Func([IDL.Bool], [], []),
    'markGetStartedCompleted' : IDL.Func([IDL.Bool], [], []),
    'markRevolutionaryUpgradesCompleted' : IDL.Func([IDL.Bool], [], []),
    'markTutorialCompleted' : IDL.Func([IDL.Bool], [], []),
    'markWelcomeCompleted' : IDL.Func([IDL.Bool], [], []),
    'markWhitepaperCompleted' : IDL.Func([IDL.Bool], [], []),
    'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'registerMiningWorker' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitMiningProof' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Text],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateDisplayName' : IDL.Func([IDL.Text], [], []),
    'updateOnboardingProgress' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateSessionStatus' : IDL.Func([IDL.Text], [], []),
    'updateVotingAbilityStatus' : IDL.Func([IDL.Bool], [], []),
    'verifyMiningProof' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };